name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4 
  - numpy=1.26.2
  - opencv-python=4.8.1.78
  - pillow=10.1.0
  - tqdm=4.66.1
  - pip
  - pip:
      - annotated-types==0.6.0
      - anyio==3.7.1
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - distro==1.8.0
      - exceptiongroup==1.1.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.1
      - idna==3.4
      - openai==1.3.3
      - playsound==1.3.0
      - pyaudio==0.2.14
      - pycparser==2.21
      - pydantic==2.5.1
      - pydantic_core==2.14.3
      - pyobjc==10.0
      - requests==2.31.0
      - sniffio==1.3.0
      - sounddevice==0.4.6
      - soundfile==0.12.1
      - speechrecognition==3.10.0
      - typing_extensions==4.8.0
      - urllib3==2.1.0
